# Generated by Django 5.2.8 on 2025-11-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_customer_options_remove_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "can cancel order")]},
        ),
    ]
