# Generated by Django 5.2.8 on 2025-12-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_orderitem_order_productimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="prduct",
            new_name="product",
        ),
    ]
